from nnws_1 import Data, Recvr
data = Data('hello ', 'text', False)
data = data()
data_c = Data('PING BODY', 'ping', True)
data_c = data_c()
data2 = Data('world', 'continuation', True)
data2 = data2()
rvr = Recvr()
r = rvr(data[0])
vars(r)
r = rvr(data_c[0])
vars(r)
r = rvr(data2[0])
vars(r)
